name: Deploy Acumatica Customization

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Enter the version name (e.g., SimpleCustomization20250329v6)'
        required: true
        type: string

jobs:
  build_and_publish:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
     
      - name: Build CustomizationPackageTools.exe
        run: |
          cd CustomizationPackageTools
          dotnet build --configuration Release
          cd ..
        shell: pwsh

      - name: Run Build Customization
        shell: pwsh
        run: |
          ./buildCustomization.ps1 "${{ github.event.inputs.versionName }}"

      - name: Run Publish Customization
        shell: pwsh
        env:
          ACUMATICA_URL: ${{ secrets.ACUMATICA_URL }}
          ACUMATICA_USERNAME: ${{ secrets.ACUMATICA_USERNAME }}
          ACUMATICA_PASSWORD: ${{ secrets.ACUMATICA_PASSWORD }}
        run: |
          ./publishCustomization.ps1 "${{ github.event.inputs.versionName }}"
