name: Deploy Acumatica Customization

on:
  push:
    tags:
      - '*'  # Trigger on any tag push
  workflow_dispatch:  # Manual trigger without requiring versionName input

jobs:
  build_and_publish:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
     
      - name: Build CustomizationPackageTools.exe
        run: |
          cd CustomizationPackageTools
          dotnet build --configuration Release
          cd ..
        shell: pwsh

      - name: Extract Version from Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: Run Build Customization
        shell: pwsh
        run: |
          ./buildCustomization.ps1 "${{ env.VERSION_NAME }}"

      - name: Run Publish Customization
        shell: pwsh
        env:
          ACUMATICA_URL: ${{ secrets.ACUMATICA_URL }}
          ACUMATICA_USERNAME: ${{ secrets.ACUMATICA_USERNAME }}
          ACUMATICA_PASSWORD: ${{ secrets.ACUMATICA_PASSWORD }}
        run: |
          ./publishCustomization.ps1 "${{ env.VERSION_NAME }}"
